import React, { useState, useRef, useEffect } from 'react';
import { useApp } from '../../context/AppContext';
import {
  Save,
  Send,
  History,
  Printer,
  Sparkles,
  MessageSquare,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  List,
  ListOrdered,
  Highlighter,
  X,
  ShieldCheck,
  Edit3,
  RefreshCw,
  AlertCircle
} from 'lucide-react';
import { VersionHistoryModal } from './VersionHistoryModal';

export const LegalDocumentEditor: React.FC = () => {
  const {
    currentUser,
    documents,
    selectedDocumentId,
    saveDocumentDraft,
    restoreDocumentVersion,
    submitDocumentForReview,
    approveDocument,
    rejectDocument,
    addInlineComment,
    theme,
    clients,
    tasks,
    markDocumentDelivered,
    renewDocument,
    templates
  } = useApp();

  const doc = documents.find(d => d.id === selectedDocumentId) || documents[0];
  const linkedTask = tasks.find(t => t.documentId === doc?.id);
  const isDelivered = linkedTask ? linkedTask.status === 'completed' : false;
  const isApproved = doc?.status === 'approved';
  const template = templates.find(t => t.id === doc?.templateId);
  const isStale = template ? doc?.templateVersionAtGeneration !== template.version : false;

  const [contentHtml, setContentHtml] = useState(doc?.content || '');
  const [showVersionModal, setShowVersionModal] = useState(false);
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [showAIDrawer, setShowAIDrawer] = useState(false);
  const [showCommentsDrawer, setShowCommentsDrawer] = useState(false);
  const [showReviewModal, setShowReviewModal] = useState(false);
  const [reviewNotes, setReviewNotes] = useState('');
  const [selectedText, setSelectedText] = useState('');
  const [commentInput, setCommentInput] = useState('');
  const [changeNoteInput, setChangeNoteInput] = useState('Updated legal clauses and variable inputs.');
  const [replyTargetId, setReplyTargetId] = useState<string | null>(null);
  const [replyInput, setReplyInput] = useState('');

  const [selectedTone, setSelectedTone] = useState<'strict' | 'balanced' | 'plain'>('strict');
  const [aiSuggestions, setAiSuggestions] = useState<string[]>([]);
  const [isAiLoading, setIsAiLoading] = useState(false);

  const editorRef = useRef<HTMLDivElement>(null);
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const isDark = theme === 'dark';

  // Detect if this document was generated by the House Rental Wizard.
  // The compiled HTML is a full <!DOCTYPE html> document — it must be rendered
  // inside an iframe so its <style> block (Times New Roman, A4, 4cm margins)
  // is applied correctly. Setting it as innerHTML of a div strips <head>/<style>.
  const isHouseWizardDoc = doc?.content?.startsWith('<!DOCTYPE') || doc?.content?.startsWith('<!');

  useEffect(() => {
    if (doc) {
      setContentHtml(doc.content);
      if (!isHouseWizardDoc && editorRef.current) {
        editorRef.current.innerHTML = doc.content;
      }
      if (isHouseWizardDoc && iframeRef.current) {
        const iframe = iframeRef.current;
        iframe.srcdoc = doc.content;
      }
    }
  }, [doc?.id, doc?.content, isHouseWizardDoc]);

  // Listen for height messages from the iframe's ResizeObserver script
  // and update the iframe element's height so the full document shows
  // without an internal scrollbar.
  useEffect(() => {
    if (!isHouseWizardDoc) return;
    const handler = (event: MessageEvent) => {
      if (
        event.data &&
        event.data.type === 'lexdraft-iframe-height' &&
        typeof event.data.height === 'number' &&
        iframeRef.current
      ) {
        iframeRef.current.style.height = `${event.data.height + 4}px`;
        iframeRef.current.style.minHeight = '297mm';
      }
    };
    window.addEventListener('message', handler);
    return () => window.removeEventListener('message', handler);
  }, [isHouseWizardDoc]);


  if (!doc) {
    return <div className="p-12 text-center text-slate-500 font-light">No document selected.</div>;
  }

  const isBoss = currentUser.role === 'boss';

  const format = (command: string, value: string | undefined = undefined) => {
    document.execCommand(command, false, value);
  };

  const handleSelection = () => {
    const selection = window.getSelection();
    if (selection && selection.toString().trim()) {
      setSelectedText(selection.toString().trim());
    }
  };

  const handleConfirmSave = () => {
    saveDocumentDraft(doc.id, contentHtml, doc.variables, changeNoteInput);
    setShowSaveModal(false);
  };

  const handleAddComment = () => {
    if (!commentInput.trim()) return;
    addInlineComment(doc.id, selectedText || 'Selected clause', commentInput);
    setCommentInput('');
    setSelectedText('');
    setShowCommentsDrawer(true);
  };

  const handlePrint = () => {
    if (isHouseWizardDoc && iframeRef.current?.contentWindow) {
      iframeRef.current.contentWindow.focus();
      iframeRef.current.contentWindow.print();
    } else {
      window.print();
    }
  };

  const handleRunAiAnalysis = () => {
    setIsAiLoading(true);
    setTimeout(() => {
      setAiSuggestions([
        'Notice period clause (Section 3) lacks protective parameters.',
        'Severability standard clause missing in boilerplate provisions.',
        'Convert Section 2 to a stricter protective tone formulation.'
      ]);
      setIsAiLoading(false);
    }, 800);
  };

  const handleInsertClause = (clauseHtml: string) => {
    setContentHtml(prev => prev + clauseHtml);
    if (editorRef.current) {
      editorRef.current.innerHTML = editorRef.current.innerHTML + clauseHtml;
    }
    setShowAIDrawer(false);
  };

  return (
    <div className={`flex flex-col h-[calc(100vh-4rem)] overflow-hidden select-none transition-colors ${
      isDark ? 'bg-slate-950 text-slate-100' : 'bg-slate-50 text-slate-900'
    }`}>
      {/* Top Document Action Bar */}
      <div className={`border-b px-6 py-3 flex items-center justify-between z-20 shrink-0 ${
        isDark ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200'
      }`}>
        <div className="flex items-center space-x-3">
          <div className="p-2 rounded-xl bg-ink-black text-paper-white dark:bg-paper-white dark:text-ink-black">
            <Edit3 className="w-3.5 h-3.5" />
          </div>
          <div>
            <div className="flex items-center space-x-2 flex-wrap gap-y-1">
              <h1 className="text-xs font-semibold text-ink-black dark:text-white leading-none">{doc.title}</h1>
              <span className="px-1.5 py-0.5 text-[9px] font-mono bg-mist-gray dark:bg-slate-800 text-slate-505 rounded-sm">
                v{doc.currentVersion}
              </span>
              <span className="px-2 py-0.5 text-[9px] font-semibold rounded-full uppercase tracking-wider bg-blush-peach text-sienna-brown dark:bg-sienna-brown dark:text-blush-peach">
                {doc.status.replace('_', ' ')}
              </span>
            </div>
            <p className="text-[10px] text-slate-400 mt-1 font-light">
              Client: <span className="font-normal text-slate-600 dark:text-slate-300">{clients.find(c => c.id === doc.clientId)?.name || 'Unknown'}</span> • Associate: {doc.authorName}
            </p>
          </div>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={() => setShowVersionModal(true)}
            className="btn-ghost py-1.5 px-3 rounded-full text-[11px] flex items-center space-x-1 cursor-pointer"
          >
            <History className="w-3 h-3 text-slate-405" />
            <span>Versions ({doc.versions.length})</span>
          </button>

          <button
            onClick={() => setShowAIDrawer(!showAIDrawer)}
            className={`btn-ghost py-1.5 px-3 rounded-full text-[11px] flex items-center space-x-1 cursor-pointer ${
              showAIDrawer ? 'bg-blush-peach dark:bg-sienna-brown border-transparent text-sienna-brown dark:text-blush-peach' : ''
            }`}
          >
            <Sparkles className="w-3 h-3" />
            <span>AI Copilot</span>
          </button>

          <button
            onClick={() => setShowCommentsDrawer(!showCommentsDrawer)}
            className="btn-ghost py-1.5 px-3 rounded-full text-[11px] flex items-center space-x-1 cursor-pointer"
          >
            <MessageSquare className="w-3 h-3 text-slate-405" />
            <span>Comments ({doc.comments.filter(c => !c.resolved).length})</span>
          </button>

          <button
            onClick={handlePrint}
            className="p-2 border border-slate-200 dark:border-slate-800 rounded-full hover:bg-slate-100 dark:hover:bg-slate-900 cursor-pointer"
            title="Print or Export PDF"
          >
            <Printer className="w-3.5 h-3.5" />
          </button>

          {!isApproved && (
            <button
              onClick={() => setShowSaveModal(true)}
              className="btn-filled py-1.5 px-4 rounded-full text-[11px] flex items-center space-x-1 cursor-pointer"
            >
              <Save className="w-3 h-3" />
              <span>Save Draft</span>
            </button>
          )}

          {isApproved ? (
            isBoss ? (
              <div className="flex items-center space-x-2">
                {!isDelivered ? (
                  <button
                    onClick={() => markDocumentDelivered(doc.id)}
                    className="px-4 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-[11px] rounded-full flex items-center space-x-1 cursor-pointer"
                  >
                    <ShieldCheck className="w-3 h-3" />
                    <span>Deliver</span>
                  </button>
                ) : (
                  <div className="px-4 py-1.5 bg-mist-gray dark:bg-slate-900 text-slate-500 dark:text-slate-400 font-semibold text-[11px] rounded-full border border-slate-200 dark:border-slate-800 flex items-center space-x-1">
                    <ShieldCheck className="w-3 h-3 text-emerald-500" />
                    <span>Delivered</span>
                  </div>
                )}
                
                <button
                  onClick={() => renewDocument(doc.id)}
                  className="px-4 py-1.5 bg-blush-peach text-sienna-brown dark:bg-sienna-brown dark:text-blush-peach border border-sienna-brown/10 rounded-full text-[11px] font-semibold transition-transform active:scale-95 flex items-center space-x-1 cursor-pointer"
                >
                  <RefreshCw className="w-3 h-3" />
                  <span>Renew</span>
                </button>
              </div>
            ) : (
              <div className="px-4 py-1.5 bg-emerald-600/10 text-emerald-600 dark:text-emerald-450 font-semibold text-[11px] rounded-full border border-emerald-500/20 flex items-center space-x-1.5">
                <ShieldCheck className="w-3 h-3" />
                <span>Sealed</span>
              </div>
            )
          ) : !isBoss ? (
            <button
              onClick={() => submitDocumentForReview(doc.id)}
              className="btn-filled py-1.5 px-4 rounded-full text-[11px] flex items-center space-x-1.5 cursor-pointer"
            >
              <Send className="w-3 h-3" />
              <span>Submit Review</span>
            </button>
          ) : (
            doc.status === 'under_review' && (
              <button
                onClick={() => setShowReviewModal(true)}
                className="btn-filled py-1.5 px-4 rounded-full text-[11px] flex items-center space-x-1.5 cursor-pointer bg-sienna-brown text-blush-peach dark:bg-blush-peach dark:text-sienna-brown border-0 hover:opacity-95"
              >
                <ShieldCheck className="w-3 h-3" />
                <span>Sign-off Action</span>
              </button>
            )
          )}
        </div>
      </div>

      {/* Editor Formatting Toolbar */}
      <div className={`border-b px-6 py-2 flex items-center space-x-2 z-10 shrink-0 text-xs overflow-x-auto no-print ${
        isDark ? 'bg-slate-900 border-slate-800 text-slate-350' : 'bg-slate-100 border-slate-200 text-slate-650'
      }`}>
        <select
          onChange={(e) => format('formatBlock', e.target.value)}
          className="input-composer text-xs py-1 px-2.5"
        >
          <option value="P">Paragraph Text</option>
          <option value="H1">Title Header (H1)</option>
          <option value="H2">Section Header (H2)</option>
          <option value="H3">Subhead (H3)</option>
        </select>

        <div className="h-4 w-px bg-slate-300 dark:bg-slate-800 mx-1" />

        <button onClick={() => format('bold')} className="p-1.5 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 cursor-pointer" title="Bold"><Bold className="w-3 h-3" /></button>
        <button onClick={() => format('italic')} className="p-1.5 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 cursor-pointer" title="Italic"><Italic className="w-3 h-3" /></button>
        <button onClick={() => format('underline')} className="p-1.5 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 cursor-pointer" title="Underline"><Underline className="w-3 h-3" /></button>
        <button onClick={() => format('strikeThrough')} className="p-1.5 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 cursor-pointer" title="Strikethrough"><Strikethrough className="w-3 h-3" /></button>

        <div className="h-4 w-px bg-slate-300 dark:bg-slate-800 mx-1" />

        <button onClick={() => format('justifyLeft')} className="p-1.5 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 cursor-pointer"><AlignLeft className="w-3 h-3" /></button>
        <button onClick={() => format('justifyCenter')} className="p-1.5 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 cursor-pointer"><AlignCenter className="w-3 h-3" /></button>
        <button onClick={() => format('justifyRight')} className="p-1.5 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 cursor-pointer"><AlignRight className="w-3 h-3" /></button>
        <button onClick={() => format('justifyFull')} className="p-1.5 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 cursor-pointer"><AlignJustify className="w-3 h-3" /></button>

        <div className="h-4 w-px bg-slate-300 dark:bg-slate-800 mx-1" />

        <button onClick={() => format('insertUnorderedList')} className="p-1.5 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 cursor-pointer"><List className="w-3 h-3" /></button>
        <button onClick={() => format('insertOrderedList')} className="p-1.5 rounded-full hover:bg-slate-200 dark:hover:bg-slate-800 cursor-pointer"><ListOrdered className="w-3 h-3" /></button>

        <div className="h-4 w-px bg-slate-300 dark:bg-slate-800 mx-1" />

        <button
          onClick={() => {
            if (selectedText) {
              setShowCommentsDrawer(true);
            }
          }}
          className={`px-3.5 py-1 rounded-full text-[10px] font-semibold flex items-center space-x-1 cursor-pointer transition-colors ${
            selectedText ? 'bg-blush-peach text-sienna-brown dark:bg-sienna-brown dark:text-blush-peach' : 'text-slate-400'
          }`}
        >
          <Highlighter className="w-3 h-3" />
          <span>Comment Selection</span>
        </button>
      </div>

      {isStale && (
        <div className={`px-6 py-3 border-b flex items-center space-x-2 text-xs font-semibold ${
          isDark ? 'bg-amber-500/10 border-amber-500/20 text-amber-250' : 'bg-amber-50 border-amber-200 text-amber-900'
        }`}>
          <AlertCircle className="w-4 h-4 text-amber-500 shrink-0" />
          <span>Notice: This document template version is stale. The master template version has been updated.</span>
        </div>
      )}

      {/* Main Editor Paper Container */}
      <div className="flex-1 flex overflow-hidden relative">
        <div className="flex-1 overflow-y-auto overflow-x-hidden bg-[#d0d0d0] dark:bg-[#08090b]">
          {isHouseWizardDoc ? (
            /* ── A4 iframe renderer for House Rental Agreement ── */
            /* Width is 100% of the flex container so no horizontal scrollbar.  */
            /* The .page div inside controls text column width + A4 proportions. */
            <iframe
              ref={iframeRef}
              srcDoc={doc.content}
              title="Legal Document — Residential Rental Agreement"
              className="a4-document-iframe"
              style={{
                width: '100%',
                height: '297mm',          /* initial height; postMessage expands it */
                border: 'none',
                display: 'block',
                background: '#ffffff',
              }}
            />
          ) : (
            /* ── Standard rich-text contentEditable for other documents ── */
            <div
              ref={editorRef}
              contentEditable={!isApproved}
              onMouseUp={handleSelection}
              onKeyUp={handleSelection}
              onInput={(e) => setContentHtml(e.currentTarget.innerHTML)}
              dangerouslySetInnerHTML={{ __html: doc.content }}
              className="legal-document-paper w-full max-w-3xl min-h-[85vh] focus:outline-none focus:ring-0 shadow-lg"
            />
          )}
        </div>

        {/* AI Assistant Drawer */}
        {showAIDrawer && (
          <div className="w-80 sm:w-96 bg-white dark:bg-slate-900 border-l border-slate-200 dark:border-slate-850 p-5 flex flex-col justify-between overflow-y-auto z-30 shadow-2xl animate-in slide-in-from-right duration-250">
            <div className="space-y-6">
              <div className="flex items-center justify-between border-b border-slate-150 dark:border-slate-800 pb-3">
                <div className="flex items-center space-x-2">
                  <Sparkles className="w-4 h-4 text-slate-550" />
                  <h3 className="text-xs font-bold uppercase tracking-wider text-ink-black dark:text-paper-white font-sohne">AI Legal Assistant</h3>
                </div>
                <button onClick={() => setShowAIDrawer(false)} className="text-slate-400 hover:text-slate-700 cursor-pointer">
                  <X className="w-4 h-4" />
                </button>
              </div>

              <div className="space-y-4">
                <button
                  onClick={handleRunAiAnalysis}
                  disabled={isAiLoading}
                  className="w-full py-2.5 bg-ink-black hover:opacity-90 dark:bg-paper-white dark:text-ink-black text-paper-white font-semibold text-xs rounded-full shadow-sm cursor-pointer disabled:opacity-50"
                >
                  {isAiLoading ? 'Analyzing Clauses...' : 'Run Variable Analysis'}
                </button>

                {aiSuggestions.map((s, idx) => (
                  <div key={idx} className="p-4 bg-mist-gray dark:bg-slate-950 rounded-2xl border border-slate-150 dark:border-slate-800 text-xs text-slate-650 dark:text-slate-350 space-y-2">
                    <p className="leading-relaxed font-light">{s}</p>
                    <button
                      onClick={() => handleInsertClause(`<h2>SEVERABILITY</h2><p>If any provision of this Agreement is held to be unenforceable, the remaining provisions shall continue in full force.</p>`)}
                      className="text-[10px] font-semibold text-sienna-brown dark:text-blush-peach hover:underline"
                    >
                      + Insert Recommended Severability Clause
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Comments Drawer */}
        {showCommentsDrawer && (
          <div className="w-80 sm:w-96 bg-white dark:bg-slate-900 border-l border-slate-200 dark:border-slate-850 p-5 flex flex-col justify-between overflow-y-auto z-30 shadow-2xl animate-in slide-in-from-right duration-250">
            <div className="space-y-6">
              <div className="flex items-center justify-between border-b border-slate-150 dark:border-slate-800 pb-3">
                <div className="flex items-center space-x-2">
                  <MessageSquare className="w-4 h-4 text-slate-550" />
                  <h3 className="text-xs font-bold uppercase tracking-wider text-ink-black dark:text-paper-white font-sohne">Inline Comments</h3>
                </div>
                <button onClick={() => setShowCommentsDrawer(false)} className="text-slate-400 hover:text-slate-700 cursor-pointer">
                  <X className="w-4 h-4" />
                </button>
              </div>

              <div className="space-y-3 bg-mist-gray/50 dark:bg-slate-950 p-4 rounded-2xl border border-slate-150 dark:border-slate-800">
                <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">
                  Text Selection: <span className="text-sienna-brown dark:text-blush-peach italic">"{selectedText || 'General Note'}"</span>
                </p>
                <textarea
                  rows={2}
                  value={commentInput}
                  onChange={(e) => setCommentInput(e.target.value)}
                  placeholder="Type comment details..."
                  className="w-full input-composer text-xs h-16 resize-none"
                />
                <button
                  onClick={handleAddComment}
                  className="w-full py-2 bg-ink-black dark:bg-paper-white text-paper-white dark:text-ink-black font-semibold text-xs rounded-full cursor-pointer"
                >
                  Post Comment
                </button>
              </div>

              <div className="space-y-3">
                {doc.comments.filter(c => !c.parentCommentId).map((cmt) => {
                  const replies = doc.comments.filter(r => r.parentCommentId === cmt.id);
                  return (
                    <div key={cmt.id} className="p-3.5 bg-mist-gray/40 dark:bg-slate-950 rounded-2xl border border-slate-150 dark:border-slate-850 space-y-2 text-xs">
                      <div className="flex items-center justify-between">
                        <span className="font-semibold text-ink-black dark:text-paper-white">{cmt.authorName}</span>
                        <span className="text-[9px] text-slate-400 font-mono">{new Date(cmt.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                      </div>

                      {cmt.selectedText && cmt.selectedText !== 'Selected clause' && cmt.selectedText !== 'General Note' && (
                        <p className="text-[10px] bg-white dark:bg-slate-900 text-slate-500 p-2 rounded-xl border border-slate-100 dark:border-slate-800 font-mono">
                          "{cmt.selectedText}"
                        </p>
                      )}
                      <p className="text-slate-650 dark:text-slate-350 leading-relaxed font-light">{cmt.commentText}</p>

                      {replies.length > 0 && (
                        <div className="pl-3 mt-2 space-y-2 border-l border-slate-200 dark:border-slate-800">
                          {replies.map(reply => (
                            <div key={reply.id} className="p-2.5 bg-white dark:bg-slate-900 rounded-xl border border-slate-100 dark:border-slate-800 space-y-1">
                              <div className="flex items-center justify-between text-[9px]">
                                <span className="font-semibold text-slate-700 dark:text-slate-350">{reply.authorName}</span>
                                <span className="text-slate-400 font-mono">{new Date(reply.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                              </div>
                              <p className="text-slate-500 dark:text-slate-400 text-[11px] leading-relaxed font-light">{reply.commentText}</p>
                            </div>
                          ))}
                        </div>
                      )}

                      <div className="flex justify-end pt-1">
                        {replyTargetId === cmt.id ? (
                          <div className="w-full space-y-2">
                            <input
                              type="text"
                              value={replyInput}
                              onChange={(e) => setReplyInput(e.target.value)}
                              placeholder="Type reply..."
                              className="w-full input-composer text-xs"
                            />
                            <div className="flex justify-end space-x-1.5">
                              <button
                                onClick={() => setReplyTargetId(null)}
                                className="px-2 py-1 text-[9px] bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-750 text-slate-600 dark:text-slate-300 rounded font-semibold"
                              >
                                Cancel
                              </button>
                              <button
                                onClick={() => {
                                  if (!replyInput.trim()) return;
                                  addInlineComment(doc.id, '', replyInput, cmt.id);
                                  setReplyInput('');
                                  setReplyTargetId(null);
                                }}
                                className="px-2.5 py-1 text-[9px] bg-ink-black dark:bg-paper-white text-paper-white dark:text-ink-black rounded font-semibold"
                              >
                                Reply
                              </button>
                            </div>
                          </div>
                        ) : (
                          <button
                            onClick={() => {
                              setReplyTargetId(cmt.id);
                              setReplyInput('');
                            }}
                            className="text-[9px] font-semibold text-sienna-brown dark:text-blush-peach hover:underline"
                          >
                            Reply
                          </button>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Save Draft Version Modal */}
      {showSaveModal && (
        <div className="fixed inset-0 bg-slate-950/40 backdrop-blur-xs z-50 flex items-center justify-center p-4">
          <div className="w-full max-w-md bg-white dark:bg-slate-900 border border-slate-150 dark:border-slate-850 rounded-[24px] shadow-2xl p-6 space-y-5 animate-page-fade">
            <div className="flex items-center space-x-2 border-b border-slate-100 dark:border-slate-800 pb-3">
              <Save className="w-4 h-4 text-slate-400" />
              <h3 className="text-base font-semibold serif-heading text-ink-black dark:text-paper-white">
                Save Version Snapshot
              </h3>
            </div>

            <div>
              <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Version Commit Message</label>
              <textarea
                rows={3}
                value={changeNoteInput}
                onChange={(e) => setChangeNoteInput(e.target.value)}
                placeholder="Detail changes made in this draft checkpoint..."
                className="w-full input-composer text-xs h-16 resize-none"
              />
            </div>

            <div className="flex items-center justify-between gap-3 pt-2">
              <button
                onClick={() => setShowSaveModal(false)}
                className="btn-ghost text-xs rounded-full flex-1 cursor-pointer"
              >
                Cancel
              </button>
              <button
                onClick={handleConfirmSave}
                className="btn-filled text-xs rounded-full flex-1 cursor-pointer"
              >
                Save Snapshot
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Partner Approval Modal */}
      {showReviewModal && (
        <div className="fixed inset-0 bg-slate-950/40 backdrop-blur-xs z-50 flex items-center justify-center p-4">
          <div className="w-full max-w-md bg-white dark:bg-slate-900 border border-slate-150 dark:border-slate-850 rounded-[24px] shadow-2xl p-6 space-y-5 animate-page-fade">
            <div className="flex items-center space-x-2 border-b border-slate-100 dark:border-slate-800 pb-3">
              <ShieldCheck className="w-4 h-4 text-slate-450" />
              <h3 className="text-base font-semibold serif-heading text-ink-black dark:text-paper-white">
                Partner Review Action
              </h3>
            </div>

            <p className="text-xs text-slate-400 font-light">
              Reviewing "{doc.title}" draft agreement.
            </p>

            <div>
              <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Feedback Notes / Instructions</label>
              <textarea
                rows={3}
                value={reviewNotes}
                onChange={(e) => setReviewNotes(e.target.value)}
                placeholder="Enter feedback notes or sign-off instructions..."
                className="w-full input-composer text-xs h-16 resize-none"
              />
            </div>

            <div className="flex items-center justify-between gap-3 pt-2">
              <button
                onClick={() => {
                  rejectDocument(doc.id, reviewNotes);
                  setShowReviewModal(false);
                }}
                className="btn-ghost text-xs rounded-full flex-1 cursor-pointer border-rose-500/20 text-rose-600 hover:bg-rose-500 hover:text-white"
              >
                Request Revisions
              </button>
              <button
                onClick={() => {
                  approveDocument(doc.id, reviewNotes);
                  setShowReviewModal(false);
                }}
                className="btn-filled text-xs rounded-full flex-1 cursor-pointer bg-emerald-600 text-white border-0 hover:bg-emerald-500"
              >
                Seal & Approve
              </button>
            </div>
          </div>
        </div>
      )}

      {showVersionModal && (
        <VersionHistoryModal
          document={doc}
          onClose={() => setShowVersionModal(false)}
          onRestore={(vNum) => restoreDocumentVersion(doc.id, vNum)}
        />
      )}
    </div>
  );
};
